In [1]:
from core import tf_util
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()

In [2]:
batch_size = 5
dim = 2
x_shape = (batch_size, dim * dim)
xp = tf.placeholder(tf.float32, shape=x_shape)
x = np.random.rand(*x_shape)

L = tf_util.vec2lower_triangle(xp, dim)

out = sess.run(L, {xp: x})

In [3]:
print(out)
print(x)
print(np.exp(x[0, 0]))
print(np.exp(x[0, 3]))

[[[ 1.8512007   0.        ]
  [ 0.0853904   1.5123539 ]]

 [[ 1.69283712  0.        ]
  [ 0.60007709  1.91648614]]

 [[ 1.22441685  0.        ]
  [ 0.52229494  2.26390576]]

 [[ 1.53929102  0.        ]
  [ 0.32693222  1.2020576 ]]

 [[ 2.0189271   0.        ]
  [ 0.11629831  1.01056957]]]
[[ 0.61583449  0.99732825  0.08539039  0.41366735]
 [ 0.52640585  0.68137442  0.6000771   0.65049337]
 [ 0.20246474  0.12256656  0.52229491  0.81709155]
 [ 0.43132193  0.91351243  0.32693222  0.18403473]
 [ 0.70256622  0.16496137  0.11629831  0.01051411]]
1.85120075581
1.51235395933


In [4]:
delta_shape = (batch_size, dim)
delta = np.random.rand(*(delta_shape))
delta_p = tf.placeholder(tf.float32, shape=delta_shape)
h1 = tf.expand_dims(delta_p, 1)  # h1_shape = batch:1:dimA
h1 = tf.batch_matmul(h1, L)    # h1_shape = batch:1:dimA
h1 = tf.batch_matmul(
    h1,
    h1,
    adj_y=True,  # Compute h1 * h1^T
)                              # h1_shape = batch:1:1
h1 = tf.squeeze(h1, [1])       # h1_shape = batch:1
output = -0.5 * h1

out2 = sess.run(output, {xp: x, delta_p: delta})

In [6]:
M1 = out[0]
P1 = np.dot(M1, M1.T)
in1 = delta[0:1]
print(P1)
print(in1)
print(-0.5 *  in1.dot(P1).dot(in1.T))
print(out2[0])

[[ 3.42694402  0.15807477]
 [ 0.15807477  2.29450583]]
[[ 0.0332264   0.93503794]]
[[-1.00984129]]
[-1.00984132]
